# Generated by Django 5.2.6 on 2025-09-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uodated_at',
            new_name='updated_at',
        ),
    ]
